name: Daily Analytics Pipeline

on:
  schedule:
    # Run at 04:00 JST (19:00 UTC previous day)
    - cron: '0 19 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  analytics-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create output directory
      run: mkdir -p output
    
    - name: Run analytics pipeline
      env:
        GA_PROPERTY_ID: ${{ secrets.GA_PROPERTY_ID }}
        STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TW_BEARER_TOKEN: ${{ secrets.TW_BEARER_TOKEN }}
      run: |
        python main.py
    
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: analytics-output-${{ github.run_number }}
        path: |
          output/
        retention-days: 30
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "Pipeline failed! Check logs for details."
        # Add notification logic here (e.g., Slack, email)